### ISSUE TITLE
0.2.2 version update imposes an upgrade of xcb -> 0.9 on consuming crates

### ISSUE THREAD

**Issue by wez** [meh/rust-xcb-util#12]
This isn't a semver friendly version bump as it requires a pretty significant source code change in order to deal with the change from xcb 0.8 -> 0.9.

I'd recommend yanking 0.2.2 and publishing 0.3 instead!

**Comment by meh** [comment]
It should be fixed now, apologies for the laziness.

**Comment by wez** [comment]
No worries: thanks for the quick response!

I wish rust/cargo had some helpers to test for this sort of issue prior to publishing a crate: this is the second issue like this I've run into with other's crates this weekend, and I'm tracking another one where I accidentally broke Send/Sync of one of my types on windows a while back.
