### ISSUE TITLE
EWMH atoms seem...weird

### ISSUE THREAD

**Issue by sector-f** [meh/rust-xcb-util#4]
In the `xcb` crate, all the atoms are constants. But for `xcb_util::ewmh`, you have to call a function on a `xcb_util::ewmh::Connection` to access the atoms. Would it be possible to make the EWMH atoms constants, or is this impossible due to a bunch of technical reasons that I don't know about?

**Comment by meh** [comment]
The EWMH atoms are loaded at runtime when the `ewmh::Connection` is created, they are not constant.
